import sys
import subprocess
import os
import time
blue = "\033[94m"
orange = "\033[93m"
yellow = "\033[33m"
purple = "\033[95m"
lime_green = "\033[92m"
red_text = "\033[91m"
reset_color = "\033[0m"

#print(f"{blue}This is blue text{reset_color}")
#print(f"{orange}This is orange text{reset_color}")
#print(f"{yellow}This is yellow text{reset_color}")
#print(f"{purple}This is purple text{reset_color}")
#print(f"{lime_green}This is lime green text{reset_color}")
#print(f"{red_text}This is red text{reset_color}")
os.system('cls' if os.name == 'nt' else 'clear')


print(f"{blue}   .       .       .       .      . ..S8@@8888888S@S.. .   .       .       .       .       .        .    {reset_color}")
time.sleep(.03)
print(f"{blue}      . .     . .     . .     . .  %88%.8 S8.88%t8.X%8@  .    . .     . .     . .     . .     . .  .   . {reset_color}")
time.sleep(.03)
print(f"{blue}  .       .       .       .  . .%@t8@8X. X8.88t;8;8 88:@SX .      .       .       .       .          .   {reset_color}")
time.sleep(.03)
print(f"{blue}.   . .     . .     . .    . .8S88X;:;X ..; 88tt .% t  ;% 88:.  .   . .     . .     . .     . .  .     . {reset_color}")
time.sleep(.03)
print(f"{blue}        . .     . .     .   .88t;;:..8.  ;X@SS@XS..%@  :: S.S           . .     . .     . .     .  .     {reset_color}")
time.sleep(.03)
print(f"{blue} . .  .     .       .    . %%88888@ S @.SS@@X@XX@@.%88%X888S8@%. .  .  .     .      .       .       . .  {reset_color}")
time.sleep(.03)
print(f"{blue}        .     . .     . . @.:;  888888XXXX@@XX@XXX8;88 8 8::%X t .        .    .  .   . .     .  .      .{reset_color}")
time.sleep(.03)
print(f"{blue}  . . .   .  .    .  .   ::8%:  .  : 8%8@@X@X@X@X@@@8;X:;:  . 8:% .  .  .   .   .         .  .    .  .   {reset_color}")
time.sleep(.03)
print(f"{blue}           .    .   .  . 8.   .   S XX@X@X@@X@@X@X@@;:8% .   .;88;.       .   .    . .  .   .  .      .  {reset_color}")
time.sleep(.03)
print(f"{blue} .  .  . .    .   .   . 8..   ... 8tt@X@XX8:tt.@XX@X8%8S . . . 8;; .. .     .    .        .      . .    .{reset_color}")
time.sleep(.03)
print(f"{blue}   .        .         . t8     ..:8;t@@S8 8SX@X8.8S@@% @ .   .. St .    .      .    . . .    .       .   {reset_color}")
time.sleep(.03)
print(f"{blue}.    .  .  .   . . . . t8@    . .:S8@X8@@XSXSXSX@8X8@X8.t.. .  .8@ . .    .  .    .        .   . .  .  . {reset_color}")

print(f"{blue}  .      .   .       . S8;X8@@XXS@ 8X%@XXSSSSSXSSXX8;@X%8SXXXXXS88..  .    .    .    .  .    .           {reset_color}")
time.sleep(.03)
print(f"{blue}    . .         .  .   t88 ;8 8%88 S @X%%S8@8ttXSXS@X;ttS88%8.88@;      .    .    .       .     . .  .  .{reset_color}")
time.sleep(.03)
print(f"{blue} .      .  .  .      . :8@.;;:t;% 88X:X @8%X.;%X8S8%t888.@%;;:tS8t     .   .   .    . . .   . .    .     {reset_color}")
time.sleep(.03)
print(f"{blue}   .  .   .     . .   . 88     .: @8tX @@ X@88tSSX%%8%88 :..   t %       .       .        .      .   . . {reset_color}")
time.sleep(.03)
print(f"{blue}.       .   . .     .  .88X .   :  8S%X@S.SS..@;XS%S%@:8::   . S;8t.   .    . .    .  .      .           {reset_color}")
time.sleep(.03)
print(f"{blue} .  . .          .   . . t8  . .;88.:%8tX@ ;:@%SX%.8%8%88t. . :8.:.  .    .     .   .   .  .   .  . .  . {reset_color}")
time.sleep(.03)
print(f"{blue}   .     . .  .    .    . 8@88%S@.X@.8 @S88@@SXS8 S:8%@X.XSt88@8t .     .    .   .       .   .   .       {reset_color}")
time.sleep(.03)
print(f"{blue}.     .         .    . . ;888@@%@Xt.8@88X;XSSSS8:X8XS8:tS@ 8%8@8t   .  .   .   .   .  .    .    .   . .  {reset_color}")
time.sleep(.03)
print(f"{blue}  .     .  . .    .    . ..S@@%888St8@XtS88SXX@88XS888%X8S@X8XSt .    .  .   .       .  .     .         .{reset_color}")
time.sleep(.03)
print(f"{blue}    . .        .    .       .X@8S@8S8 tSSSXSS8XXXSS% 8S@X%8XS...   .            . .       .      . .  .  {reset_color}")
time.sleep(.03)
print(f"{blue} .      . .  .   .    . . .   .8X;XXXSSSXSSX8SXSS8SXSSSXtS8:.  ..    .  .  .  .     .  .    . .          {reset_color}")
time.sleep(.03)
print(f"{blue}  . .         .   .        . ..S88XSSXSS8@@SXS88SXSSSXX8S.     .  .      .     .    .   .      .  . . . {reset_color}")
time.sleep(.03)
print(f"{blue}.     .  . .    .   .   .     .  ;8; S@XS%SSXXSS8@X% 8; .   .   .   . .    . .   .    .   .  .          {reset_color}")
time.sleep(.03)
print(f"{blue}  .          .        .   .    .    .tXt;@ 8 S;.XX;:..    .   .  .      .         .     .      . .  .  .{reset_color}")
time.sleep(.03)
print(f"{blue}    . . .  .   .  . .       .     .  . :%;;;;t%:...    .    .  .   .  .   .  . .    .     . .        .  {reset_color}")
time.sleep(.03)
print(f"{blue}. .           .        .  .    . .    . .:8@@@8.S .   .   .       .      .        .   . .      .  . .    {reset_color}")
time.sleep(.03)
print(f"{blue}    .  .  . .    . .     .  .       . . .X :.: 8% .     .   . . .    .      .  .    .     .  .         . {reset_color}")
time.sleep(.03)
print(f"{blue}  .      .     .     . .      .  .    .  ;8@t@8.S . . .            .   .  .     .  .   .       . .  .    {reset_color}")
time.sleep(.03)
print(f"{blue}    . .     .    .....   .....   ..  . .:t;@:St;8..  . .... ......  ....    . .      .   . .         .  .{reset_color}")
time.sleep(.03)
print(f"{blue} .      . .   .        .       .    .     8t;X@ S .   .                  .       .           .  . .      {reset_color}")
time.sleep(.03)
print(f"{blue}   .  .     .  .{lime_green} t@ S @. @  % SS  : . %8   8tX% . :. :    %.8X   % 8  S.t {blue}.  .  .  .  . .  .   .    . .  {reset_color}")
time.sleep(.03)
print(f"{blue}        .     ..{lime_green}8:  8;; @:  tX% @X : .8. : @X. t.8t     %8 XXS : ;;8 .@X {blue} .        .        .    .     .{reset_color}")
time.sleep(.03)
print(f"{blue}  .   .   .  .. {lime_green}8:   8: @   %SS 8X : ; X.S 8:%X;:8t .;;:t  @.S:  :;@ ... {blue}   . .  .    . .      .    .   {reset_color}")
time.sleep(.03)
print(f"{blue}            . ..{lime_green}88XSS8 .@. .tX% @X :..@%%t Xt@.  8; %S@%X8.XS8tt ;t@ .%8 {blue}.      .   .     . .     .   . {reset_color}")
time.sleep(.03)
print(f"{blue}  .   .       . {lime_green}8  .t8@ X S % @ .SX 8SX X 8%88  tX. X; X:8 8@ X S   XS:8 {blue}.  .     .    .      . .   .   {reset_color}")
time.sleep(.03)
print(f"{blue} .         .  .      . .  .     ..           .      ...  .             .      . .     .   .  .          .{reset_color}")
time.sleep(.03)
print(f"{blue}   . .  .   .   . .   .  .    .   . .      . .   ..      .            ...  .      .  .     .    .  .  .  {reset_color}")
time.sleep(.03)
print(f"{blue} .        .  {purple} ::  ::..:. :: . .  .:  ... . .:. .  ;. :;. :; .. . .;. . .::....{blue} .       . .    .   .      {reset_color}")
time.sleep(.03)
print(f"{blue}  . . . .  . {purple}8%t%:8S @@X:8% S8@@.@tt:X X.X.@8@ . %S8 %%:tSSS:@:X SSX @tt8t @8@{blue}  .  .        .   .   . .  {reset_color}")
time.sleep(.03)
print(f"{blue}    .      . {purple}@88@tSX S8:%@8.X888;888:X.X88;S8%   8XS S8:SSS;;88X.S88.SS:;% ;8S{blue} .    . .  .    .         .{reset_color}")
time.sleep(.03)
print(f"{blue}  .   .  .   {purple}.%% :;  :: :X% :;S:.XX..: :X: ;X: . ;t..tS..;%.:%S: ;t;::. .. :%.{blue}   .         .     . .  .  {reset_color}")


print(f"{lime_green}  _      ____          _____ _____ _   _  _____   {reset_color}")
time.sleep(.03)
print(f"{lime_green} | |    / __ \   /\   |  __ \_   _| \ | |/ ____|_ {reset_color}")
time.sleep(.03)
print(f"{lime_green} | |   | |  | | /  \  | |  | || | |  \| | |  __(_){reset_color}")
time.sleep(.03)
print(f"{lime_green} | |   | |  | |/ /\ \ | |  | || | | . ` | | |_ |  {reset_color}")
time.sleep(.03)
print(f"{lime_green} | |___| |__| / ____ \| |__| || |_| |\  | |__| |_ {reset_color}")
time.sleep(.03)
print(f"{lime_green} |______\____/_/    \_\_____/_____|_| \_|\_____(_){reset_color}")
print(f"{red_text}ROLENSEC.©2018-2024{reset_color}")
time.sleep(1)
